### ISSUE TITLE
Partial JPEG recompression

### ISSUE THREAD

**Issue by kamemak** [lossless-jpg/data#1]
I saw @nicolas-raoul  [post about partical JPEG recompression](https://github.com/k3b/LosslessJpgCrop/issues/33).
I think [Jpegcoll](https://sites.google.com/view/jpegcoll/home_en) is one of the solution for your requirement.
If you are interested in another lossless operations, you should check [Betterjpeg](https://www.betterjpeg.com/).

Almost apps which have JPEG lossless operations are based on [IJG code](https://www.ijg.org/).
These apps are listed [here](https://jpegclub.org/losslessapps.html).
But these apps have only rotate, flip and crop as lossless operation except above two probably.

**Comment by nicolas-raoul** [comment]
@kamemak

Thanks a lot for these wonderful tips! I do not have any Windows computer (only Linux & Mac), so I can not try them, but they look very promising. Indeed it looks like both can be used to retouch a part of an image without recompressing the rest of the image, which means they are usable for blurring.

Actually, my goal is to make users of the [Wikimedia Commons app](https://commons-app.github.io) (_the official app to upload pictures to Wikipedia/etc_) avoid losing JPEG quality when uploading pictures.

I just edited [the app's documentation](https://commons-app.github.io/docs.html#editing) to suggest them to use your app [JPEG Cropper](https://play.google.com/store/apps/details?id=jp.kame.jpegcropper).

How about adding a partial **blurring** feature to JPEG Cropper? That feature could make your app popular among Wikipedia uploaders :-)

**Comment by kamemak** [comment]
I had implemented blur like operation exprimentaly.
Please check [AJT](https://play.google.com/store/apps/details?id=jp.kame.ajt) which is porting of JPEGTran to Android GUI.
The operation is hard to find, check the following step figure.

![AJT_Pexlization](https://user-images.githubusercontent.com/103130812/162580701-65996a38-e131-4520-811f-d7bba6f08f1b.png)

Curently the implementation is not practical for using.
But isn't it roughly suitabable for your requirement?

**Comment by nicolas-raoul** [comment]
Thank you for the great tip!
AJT is very powerful.
Did you manage to use the jpegtran in [Android's source code](https://cs.android.com/android/platform/superproject/+/master:external/libjpeg-turbo/jpegtran.c)? Or are you using JNI? If you agree, I encourage you to upload AJT's source code to GitHub. 🙂

I added AJT to https://github.com/lossless-jpg/data and https://commons-app.github.io/docs.html.

By the way, I noticed a few things that might be improved in this otherwise perfect app:
- `defalut`→`default`
- `exitst`→`exists`
- `rorate`→`rotate`
- How about implementing an intent, so that I can "share" a picture to AJT, and it gets automatically selected as the input?

People upload a lot of pictures to Wikipedia with lots of faces to blur ([example](https://commons.wikimedia.org/wiki/File:Protestors_against_2022_Russia_invasion_of_Ukraine,_in_Shibuya_Hachiko_square.jpg)), I am not sure they will have the patience to run AJT to pixelize each face, unfortunately. 😅 I think blurring could be worth its own app, with:
- Configurable grain size.
- Ability to blur several areas without having to save→open→save→open→save many times.

**Comment by kamemak** [comment]
Yes, I agree with your two points of improvement.
AJT is old and has a poor UI, so a new app for pixelization should be developed.
I will consider it.
Please wait patient.

**Comment by nicolas-raoul** [comment]
I am glad to hear that you are willing to consider it.
In any case, please feel free to comment here at any time, for instance if you find interesting apps, or if you release any new app, or if you find or write anything related to lossless. 🙂

**Comment by kamemak** [comment]
As a 1st step, I released [this repository](../../../kamemak/ajpegtran_example).
The repository contains example code for Android application uses Jpegtran.
I hope this makes lossless retouch application can be developed easily.

Pixelization operation is included in the library, but size is 8x8 only, and execute once currently.

As a 2nd step, I released [this repository](../../../kamemak/jpegtran_pixelization) to modify the above.
This extended Jpegtran can execute pixelization with multi sizes muliti times in a call.

Next step, easy-to-use, light GUI is needed.
I will consider it.
If you like, please develop GUI yourself.

## Example of pixelization
### Original image
![DSC05297_](https://user-images.githubusercontent.com/103130812/167303395-8ae2cf5c-fb12-48b5-a41c-f0b4a3e9353d.JPG)

### Specified options
`jpegtran.exe -optimize -pix 240x240+0+384 -pix 240x240+320+128@3@3 -pix 240x192+464+384@2@1 -pix 480x320-128-64@8@8 input.jpg output.jpg`

### Pixelized image
Pixelization size is variable and a rectangle can be specified.  
![DSC05297__](https://user-images.githubusercontent.com/103130812/167303402-87a16269-abb8-4b35-bf54-d96a7bfdc16f.jpg)

### Difference image
50% gray is same pixel.
The color changes from 50% gray in proportion to the difference.   
![DSC05297diff](https://user-images.githubusercontent.com/103130812/167303417-133510e9-0fcd-4299-9fd2-cdf957b46a5f.png)

**Comment by nicolas-raoul** [comment]
Wonderful!
Thank you so much for the two GitHub projects, that is very generous of you, and extremely helpful. I started making plans to integrate your code directly into the Wikimedia Commons app (probably as a library). :-)

**Comment by kamemak** [comment]
I created [this branch](../../../kamemak/ajpegtran_example/tree/pixelization_extension)  which is merged 'jpegtran_extension' features.
Multi-sized pixelization could be executed on my Android simulator.
Please refer to this if you like.

If you want to modify the original IJG code to create a your own library, please refer to the following files.
The essense of pixelization is implemented only in these files.
- transupp.c
- transupp.h
- jpegtran.c (ajpegtran.c)

The pxelization option `-pix WxH+X+Y@N@Ma` is difficult to understand, I think.
I will describe about it.

**Comment by kamemak** [comment]
@nicolas-raoul 

I released a new version of JpegCropper on PlayStore.
A new operation 'Pixelate' is implemented.
You can pixelate up to 16 areas and change coordinate and pixelate size with real time preview.
Please check it.

**Comment by nicolas-raoul** [comment]
Wonderful! :-)
It seems to work great: https://github.com/lossless-jpg/data/blob/main/samples/JPEG-Cropper/blurred_comparison.jpg
The UI felt very pleasant to use, and I really appreciate the ability to choose the granularity (rough/fine).
